[package]
name = "chap11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0.192"
serde_json = "1.0.108"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 1
